"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Modal } from "@/components/ui/modal";
import { BrainCircuit, ArrowLeft, CheckCircle2, XCircle } from "lucide-react";

export default function HallucinationAssessmentPage() {
  const { id } = useParams() as { id: string };
  const router = useRouter();

  const [status, setStatus] = useState<"loading" | "picking" | "grading" | "result">("loading");
  const [statements, setStatements] = useState<string[]>([]);
  const [attemptId, setAttemptId] = useState<string>("");
  const [modalState, setModalState] = useState<{isOpen: boolean, title: string, desc: string}>({isOpen: false, title: '', desc: ''});
  
  const [selectedIdx, setSelectedIdx] = useState<number | null>(null);
  const [explanation, setExplanation] = useState("");
  
  const [result, setResult] = useState<any>(null);

  useEffect(() => {
    // Generate hallucination on mount
    const generate = async () => {
      try {
        const res = await fetch("/api/ai/hallucination-generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ conceptId: id }),
        });
        if (!res.ok) throw new Error("Failed to generate");
        const data = await res.json();
        setStatements(data.statements);
        setAttemptId(data.attemptId);
        setStatus("picking");
      } catch (e) {
        console.error(e);
        setModalState({ isOpen: true, title: "Error", desc: "Failed to load assessment" });
      }
    };
    generate();
  }, [id]);

  const handleSubmit = async () => {
    if (selectedIdx === null || !explanation.trim()) return;
    setStatus("grading");

    try {
      const res = await fetch("/api/ai/hallucination-grade", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          attemptId,
          userPickIndex: selectedIdx,
          userExplanation: explanation,
        }),
      });
      if (!res.ok) throw new Error("Failed to grade");
      const data = await res.json();
      setResult(data);
      setStatus("result");
    } catch (e) {
      console.error(e);
      setModalState({ isOpen: true, title: "Error", desc: "Failed to grade assessment" });
      setStatus("picking");
    }
  };

  return (
    <main className="min-h-screen p-8 flex flex-col items-center pt-24" style={{ backgroundColor: "#F8F4EC" }}>
      <div className="max-w-3xl w-full space-y-8">
        
        <div className="flex items-center gap-4">
          <button 
            onClick={() => router.push('/assess')}
            className="p-2 rounded-full hover:bg-[#EDE8DE] transition-colors"
          >
            <ArrowLeft className="w-5 h-5 text-[#2D2A26]" />
          </button>
          <div>
            <div className="flex items-center gap-2 text-[#8A7D6B] font-mono text-sm font-bold uppercase tracking-wider">
              <BrainCircuit className="w-4 h-4" />
              Spot the AI Hallucination
            </div>
          </div>
        </div>

        {status === "loading" && (
          <div className="flex flex-col items-center justify-center py-32 space-y-6">
            <div className="w-12 h-12 border-4 border-[#2D2A26] border-t-transparent rounded-full animate-spin"></div>
            <p className="font-mono font-bold text-[#2D2A26]">AI is generating 2 truths and 1 lie...</p>
          </div>
        )}

        {(status === "picking" || status === "grading") && (
          <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <p className="text-xl font-medium leading-relaxed text-[#2D2A26]">
              Below are three statements generated by the AI. Two are true, but one is a subtle hallucination. 
              Which one is false?
            </p>

            <div className="space-y-4">
              {statements.map((stmt, idx) => (
                <div 
                  key={idx}
                  onClick={() => setSelectedIdx(idx)}
                  className={`p-6 rounded-2xl border-2 cursor-pointer transition-all ${selectedIdx === idx ? 'bg-[#F0ECE2] border-[#2D2A26] shadow-md' : 'bg-[#FFFDF8] border-[#E8E2D8] hover:border-[#D0C9BC]'}`}
                >
                  <div className="flex gap-4">
                    <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center shrink-0 mt-0.5 ${selectedIdx === idx ? 'border-[#2D2A26]' : 'border-[#D0C9BC]'}`}>
                      {selectedIdx === idx && <div className="w-3 h-3 bg-[#2D2A26] rounded-full" />}
                    </div>
                    <p className="text-[#2D2A26] leading-relaxed">{stmt}</p>
                  </div>
                </div>
              ))}
            </div>

            {selectedIdx !== null && (
              <div className="space-y-4 animate-in fade-in duration-300">
                <label className="block text-sm font-bold uppercase tracking-wider text-[#8A7D6B] font-mono">
                  Why is this wrong?
                </label>
                <Textarea 
                  value={explanation}
                  onChange={e => setExplanation(e.target.value)}
                  placeholder="Explain the error in the statement you selected..."
                  className="min-h-[120px] rounded-2xl resize-none text-base p-4 bg-[#FFFDF8] border-2 border-[#E8E2D8] focus-visible:border-[#2D2A26] focus-visible:ring-0"
                />
                
                <div className="flex justify-end pt-4">
                  <Button 
                    onClick={handleSubmit}
                    disabled={!explanation.trim() || status === "grading"}
                    className="h-12 rounded-xl px-8 font-bold font-mono transition-transform hover:scale-[1.02] active:scale-[0.98] bg-[#2D2A26] text-[#F8F4EC]"
                  >
                    {status === "grading" ? "Grading..." : "Submit Answer"}
                  </Button>
                </div>
              </div>
            )}
          </div>
        )}

        {status === "result" && result && (
          <div className="space-y-8 animate-in zoom-in-95 duration-500">
            <div className={`p-8 rounded-3xl border-2 flex flex-col items-center text-center space-y-4 ${result.pick_correct ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}`}>
              {result.pick_correct ? (
                <CheckCircle2 className="w-16 h-16 text-green-600" />
              ) : (
                <XCircle className="w-16 h-16 text-red-600" />
              )}
              <h2 className={`text-2xl font-bold font-mono ${result.pick_correct ? 'text-green-900' : 'text-red-900'}`}>
                {result.pick_correct ? "You spotted the lie!" : "You got tricked!"}
              </h2>
              
              <div className="w-full h-px bg-black/10 my-4" />
              
              <div className="text-left w-full space-y-4">
                <div>
                  <span className="text-xs font-bold uppercase tracking-wider text-black/50 font-mono">Explanation Quality</span>
                  <div className="flex items-end gap-2">
                    <span className="text-3xl font-bold font-mono">{result.explanation_quality}</span>
                    <span className="text-sm font-mono text-black/50 mb-1">/100</span>
                  </div>
                </div>
                <div>
                  <span className="text-xs font-bold uppercase tracking-wider text-black/50 font-mono">Feedback</span>
                  <p className="text-lg leading-relaxed text-black/80 mt-1">{result.feedback_text}</p>
                </div>
              </div>
            </div>

            <div className="flex justify-center">
              <Button 
                onClick={() => router.push('/assess')}
                className="h-12 rounded-xl px-8 font-bold font-mono transition-transform hover:scale-[1.02] active:scale-[0.98] bg-[#2D2A26] text-[#F8F4EC]"
              >
                Back to Assessment Hub
              </Button>
            </div>
          </div>
        )}

      </div>
      <Modal 
        isOpen={modalState.isOpen}
        onClose={() => setModalState({ ...modalState, isOpen: false })}
        title={modalState.title}
        description={modalState.desc}
        confirmText="OK"
      />
    </main>
  );
}
